/* Generated by toki v1.10.0 — do not edit */

export const colorBackgroundBase = '#100a1c';
export const colorBackgroundTopGlow = '#201e40';
export const colorBackgroundBottomGlow = '#261226';
export const colorSurfaceDefault = 'rgba(32, 30, 64, 0.6)';
export const colorSurfaceHover = 'rgba(45, 212, 191, 0.08)';
export const colorBorderDefault = 'rgba(255, 255, 255, 0.08)';
export const colorBorderHover = 'rgba(45, 212, 191, 0.3)';
export const colorAccentDefault = '#2dd4bf';
export const colorAccentHover = '#5ee8d4';
export const colorStatusPositive = '#4ade80';
export const colorStatusPositiveBackground = 'rgba(34, 197, 94, 0.18)';
export const colorStatusWarning = '#f87171';
export const colorStatusWarningBackground = 'rgba(248, 113, 113, 0.15)';
export const colorTextPrimary = '#ffffff';
export const colorTextSecondary = 'rgba(255, 255, 255, 0.55)';
export const colorBrandHuemulDark = '#85422b';
export const colorBrandHuemulLight = '#b45b38';
export const colorBrandStroke = '#1d1d1b';
export const typographyBody = 'Fira Sans, Droid Sans, Helvetica Neue, sans-serif';
export const typographyHeading = 'Inconsolata, monospace';
export const spacingRadius = '6px';
export const layoutMaxWidth = '68rem';

export const tokens = {
  color: {
    background: {
      base: '#100a1c',
      topGlow: '#201e40',
      bottomGlow: '#261226',
    },
    surface: {
      default: 'rgba(32, 30, 64, 0.6)',
      hover: 'rgba(45, 212, 191, 0.08)',
    },
    border: {
      default: 'rgba(255, 255, 255, 0.08)',
      hover: 'rgba(45, 212, 191, 0.3)',
    },
    accent: {
      default: '#2dd4bf',
      hover: '#5ee8d4',
    },
    status: {
      positive: '#4ade80',
      positiveBackground: 'rgba(34, 197, 94, 0.18)',
      warning: '#f87171',
      warningBackground: 'rgba(248, 113, 113, 0.15)',
    },
    text: {
      primary: '#ffffff',
      secondary: 'rgba(255, 255, 255, 0.55)',
    },
    brand: {
      huemulDark: '#85422b',
      huemulLight: '#b45b38',
      stroke: '#1d1d1b',
    },
  },
  typography: {
    body: 'Fira Sans, Droid Sans, Helvetica Neue, sans-serif',
    heading: 'Inconsolata, monospace',
  },
  spacing: {
    radius: '6px',
  },
  layout: {
    maxWidth: '68rem',
  },
} as const;

export type TokenCategory = keyof typeof tokens;
