/* Generated by toki v1.10.0 — do not edit */

export declare const colorBackgroundBase: string;
export declare const colorBackgroundTopGlow: string;
export declare const colorBackgroundBottomGlow: string;
export declare const colorSurfaceDefault: string;
export declare const colorSurfaceHover: string;
export declare const colorBorderDefault: string;
export declare const colorBorderHover: string;
export declare const colorAccentDefault: string;
export declare const colorAccentHover: string;
export declare const colorStatusPositive: string;
export declare const colorStatusPositiveBackground: string;
export declare const colorStatusWarning: string;
export declare const colorStatusWarningBackground: string;
export declare const colorTextPrimary: string;
export declare const colorTextSecondary: string;
export declare const colorBrandHuemulDark: string;
export declare const colorBrandHuemulLight: string;
export declare const colorBrandStroke: string;
export declare const typographyBody: string;
export declare const typographyHeading: string;
export declare const spacingRadius: string;
export declare const layoutMaxWidth: string;
