/* Generated by toki v1.10.0 — do not edit */

export type ColorToken =
  | 'color.background.base'
  | 'color.background.top-glow'
  | 'color.background.bottom-glow'
  | 'color.surface.default'
  | 'color.surface.hover'
  | 'color.border.default'
  | 'color.border.hover'
  | 'color.accent.default'
  | 'color.accent.hover'
  | 'color.status.positive'
  | 'color.status.positive-background'
  | 'color.status.warning'
  | 'color.status.warning-background'
  | 'color.text.primary'
  | 'color.text.secondary'
  | 'color.brand.huemul-dark'
  | 'color.brand.huemul-light'
  | 'color.brand.stroke';

export type TypographyToken = 'typography.body' | 'typography.heading';

export type SpacingToken = 'spacing.radius';

export type LayoutToken = 'layout.max-width';

export type TokenName = ColorToken | TypographyToken | SpacingToken | LayoutToken;
